### ISSUE TITLE
Remove @cookiengineer Maintainer of this Fork

### ISSUE THREAD

**Issue by alicemargatroid** [tenacityteam/tenacity#102] opened 2021-07-06 23:28 UTC
# Why write this
I'm writing this because, due to @cookiengineers absolutely vile post, we should remove him as maintainer ASAP (if not already done) and ban him from this repo.

Feel free to downvote, it'll just make my analysis richer.

## Appeal to harm others
>Please, if you have the time, report the https://github.com/Sneeds-Feed-and-Seed/sneedacity project to GitHub as a hate speech, violence and harassment insinuating project). Report every single member contributing in this fork, because they were part of the harassment movement against me and my family.

This is categorically untrue and just another form of the same attacks you experienced:
1. Sneeds-Feed-And-Seed is not a reference to hate speech: it's a Simpsons reference.
2. The repo, however it was created, is just code: It isn't magically imbued with the authors bad intentions.
3. Not every member of that repo was part of that harassment movement: that's collective punishment .
4. This is against github policy

Bad look my dude. Don't become the very thing harming you. Don't wish harm on other people who may be innocent.

## Inconsistency in Physical Harm
>As the first people were literally arriving at my place of living, where they knocked on my doors and windows to scare us, I am hereby officially stepping down as a maintainer of this project.

vs

>They are physically harming people, in real life. Be aware of anything you do BEFORE trying to do the right thing.

and

>4chan successfully bullied me out in order to have their fucked up sneedacity fork. A fork that was finally created with blood, quite literally.

These  statements conflict. Simply arriving at your place of living is not "physical harm", neither is knocking on doors and windows. Intimidation, sure. Physical harm? No. So was someone actually physically harmed or is this hyperbole?

Oh wait, he won't disclose information. He's just implying it. In an intellectually dishonest fashion.  

So, while also throwing shade on innocent people who had nothing to do with this, you are escalating the imagined harm they did. Where's the blood?

## Inconsistency in Anon
>This is not cancel culture. This is not anon. This is tyranny, oppression and senseless physical violence. Something the *anon movement* never stood for in the beginning.

vs 

>4chan people made up stories about me posting here, posting there. Faking sceenshots, calling out even themselves as "cookie faggot" because they cannot verify any source of information they use as "source of truth" for their executive actions. *I never posted on 4chan, and I never will.* This site is the most disgusting place in the whole world, and I think all the people that are active in /g/ should get put in jail and be ashamed of themselves for making the world a worse place than it already is.

The "anon movement" is from 4chan, notably /b/ since around 2004. Yet you've never been to 4chan.  
Makes sense.
No further comment.

## Collective Punishment and Hate
>4chan people made up stories about me posting here, posting there. Faking sceenshots, calling out even themselves as "cookie faggot" because they cannot verify any source of information they use as "source of truth" for their executive actions. I never posted on 4chan, and I never will. This site is the most disgusting place in the whole world, and I think all the people that are active in /g/ should get put in jail and be ashamed of themselves for making the world a worse place than it already is.

Do I really need to spell out why _thinking people you don't even know should be in jail because some of them might be assholes_ is evil?

1. /g/ is a major hub for programmers
2. It has 15 thousand posts per day from over a thousand posters
3. Nearly _no one_ from /g/ did anything to harm this project
4. Collective punishment is unjust
5. So is shaming people _who had nothing to do with this_

Seriously, this is not merely a bad look but moving into being just as evil and hateful as the people who attacked you

## Further Escalation
>The relevant 4chan threads about "sneedacity" (which is equivalent for harassing me):

This is flat out despicable. You are equating _talking about a name_ or _being part of a repo_ as being harassing towards you.

This is not true by any definition of harassment, and it is intellectually dishonest to suggest it is true.
You are smearing innocent people and escalating rhetoric against them while rallying people to attack them.

This is exactly what happened to you, and you should be ashamed.

## Conclusion
@cookiengineer has violated github TOS, threatened others, and been a threat to others.
He should be removed and banned, and not allowed to contribute to this repo at all, for the good of all.

_Originally posted by @alicemargatroid in https://github.com/tenacityteam/tenacity/issues/99#issuecomment-875135643_

**Comment by alicemargatroid** [comment] 2021-07-06 23:30
@emabrey I'm not arguing in bad faith and it is intellectually dishonest you would accuse me of such rather than attack my argument and points.

**Comment by emabrey** [comment] 2021-07-06 23:31
Making an issue to further harass @cookiengineer by pretending he is being kicked out as opposed to stepping down is a dishonest tactic. More to the point, it is a duplicate of #99.

**Closed by emabrey** 2021-07-06 23:31 UTC
Labels: duplicate, invalid
